const LOGIN = "LOGIN_HERE";
const PASSWORD = "PASSWORD_HERE";

const API_KEY = 'GOOGLE_CUSTOM_SEARCH_API_KEY';
const LODESTONE_CX = 'LODESTONE_CUSTOM_SEARCH_CX';
const LODESTONE_SERVER = "LODESTONE_SERVER_YOURE_ON";
const WIKI_CX = 'RPC_WIKI_CUSTOM_SEARCH_CX';

module.exports.LOGIN = LOGIN;
module.exports.PASSWORD = PASSWORD;
module.exports.API_KEY = API_KEY;
module.exports.LODESTONE_CX = LODESTONE_CX;
module.exports.LODESTONE_SERVER = LODESTONE_SERVER;
module.exports.WIKI_CX = WIKI_CX;